
CREATE DATABASE testingdb;

USE testingdb;

DECLARE @TIME1 AS DATETIME2='2000-06-12';
DECLARE @TIME2 AS DATETIME2='2012-04-05';
DECLARE @NOW AS DATETIME2='2020-03-06';
DECLARE @UNDEFINED AS DATETIME2='9999-12-31';

CREATE TABLE PERSON (
            ID INTEGER NOT NULL,
            DELETED_AT DATETIME2 NOT NULL,
            CONSTRAINT PK_PERSON PRIMARY KEY (ID, DELETED_AT),
            MODIFIED_AT DATETIME2 NOT NULL,
            NAME VARCHAR(50) NOT NULL
);

-- ================
--     1 TABLE
-- ================

-- ADD INITIAL VALUES TO 1 TABLE
INSERT INTO PERSON VALUES (1, @UNDEFINED, @TIME1, 'John');
INSERT INTO PERSON VALUES (2, @UNDEFINED, @TIME1, 'Anthony');

-- SOFT DELETE
UPDATE PERSON SET DELETED_AT = @TIME2 WHERE ID = 1 AND DELETED_AT = @UNDEFINED;

-- SOFT UPDATE
INSERT INTO PERSON SELECT ID, @TIME2, MODIFIED_AT, NAME FROM PERSON WHERE ID = 2 AND DELETED_AT = @UNDEFINED;
UPDATE PERSON SET NAME = 'Anthony2', MODIFIED_AT = @TIME2 WHERE ID = 2 AND DELETED_AT = @UNDEFINED;

SET @NOW = '2020-03-08';

INSERT INTO PERSON SELECT ID, @NOW, MODIFIED_AT, NAME FROM PERSON WHERE ID = 2 AND DELETED_AT = @UNDEFINED;
UPDATE PERSON SET NAME = 'Anthony3', MODIFIED_AT = @NOW WHERE ID = 2 AND DELETED_AT = @UNDEFINED;
-- ALL DATA
SELECT * FROM PERSON;
-- DATA AT THE CERTAIN MOMENT
SELECT * FROM PERSON WHERE DELETED_AT >= '2015-01-01' AND MODIFIED_AT <= '2015-01-01';

-- DROP TABLES

DELETE PERSON;

-- ===================
--    2 TABLES, 1:M
-- ===================

-- CREATE TABLES

CREATE TABLE PHONE(ID INTEGER NOT NULL,
                   DELETED_AT DATETIME2 NOT NULL,
                   CONSTRAINT PK_PHONE PRIMARY KEY (ID, DELETED_AT),
                   MASTER_ID INTEGER NOT NULL,
                   MASTER_DELETED_AT DATETIME2 NOT NULL,
                   CONSTRAINT FK_PERSON FOREIGN KEY (MASTER_ID, MASTER_DELETED_AT) REFERENCES PERSON(ID, DELETED_AT) ON UPDATE CASCADE,
                   MODIFIED_AT DATETIME2 NOT NULL,
                   NUMBER VARCHAR(50) NOT NULL);


-- ADD INITIAL VALUES TO BOTH TABLES
INSERT INTO PERSON VALUES (1, @UNDEFINED, @TIME1, 'John');
INSERT INTO PHONE VALUES (1, @UNDEFINED, 1, @UNDEFINED, @TIME1, '123');
INSERT INTO PHONE VALUES (2, @UNDEFINED, 1, @UNDEFINED, @TIME1, '456');
INSERT INTO PHONE VALUES (3, @UNDEFINED, 1, @UNDEFINED, @TIME1, '789');
SELECT * FROM PERSON LEFT JOIN PHONE P on PERSON.ID = P.MASTER_ID and PERSON.DELETED_AT = P.MASTER_DELETED_AT;


-- SOFT UPDATE PERSON
INSERT INTO PERSON SELECT ID, @TIME2, MODIFIED_AT, NAME FROM PERSON WHERE ID = 1 AND DELETED_AT = @UNDEFINED;
INSERT INTO PHONE (ID, DELETED_AT, MASTER_ID, MASTER_DELETED_AT, MODIFIED_AT, NUMBER) SELECT ID, @TIME2, MASTER_ID, @TIME2, MODIFIED_AT, NUMBER FROM PHONE WHERE MASTER_ID = 1 AND DELETED_AT = @UNDEFINED;
UPDATE PERSON SET NAME = 'John2', MODIFIED_AT = @TIME2 WHERE ID = 1 AND DELETED_AT = @UNDEFINED;
SELECT PERSON.NAME, P.NUMBER, PERSON.MODIFIED_AT, PERSON.DELETED_AT FROM PERSON LEFT JOIN PHONE P ON PERSON.ID = P.MASTER_ID AND PERSON.DELETED_AT = P.MASTER_DELETED_AT WHERE PERSON.MODIFIED_AT <= '2019-03-06' AND '2019-03-06' <= PERSON.DELETED_AT AND P.MODIFIED_AT <= '2019-03-06' AND '2019-03-06' <= P.DELETED_AT;

-- SOFT DELETE PERSON
UPDATE PERSON SET DELETED_AT = @NOW WHERE ID = 1 AND DELETED_AT = @UNDEFINED;
UPDATE PHONE SET DELETED_AT = @NOW WHERE MASTER_ID = 1 AND DELETED_AT = @UNDEFINED;
SELECT * FROM PERSON LEFT JOIN PHONE P ON PERSON.ID = P.MASTER_ID AND PERSON.DELETED_AT = P.MASTER_DELETED_AT WHERE '2010-03-06' BETWEEN PERSON.MODIFIED_AT AND PERSON.DELETED_AT AND '2010-03-06' BETWEEN P.MODIFIED_AT AND P.DELETED_AT;
SELECT * FROM PERSON LEFT JOIN PHONE P ON PERSON.ID = P.MASTER_ID AND PERSON.DELETED_AT = P.MASTER_DELETED_AT WHERE '2030-03-06' BETWEEN PERSON.MODIFIED_AT AND PERSON.DELETED_AT AND '2030-03-06' BETWEEN P.MODIFIED_AT AND P.DELETED_AT;

DELETE PHONE;
DELETE PERSON;

-- ===================
--   2 TABLES, 1:0-1
-- ===================

CREATE TABLE PHOTO(ID INTEGER NOT NULL,
                   DELETED_AT DATETIME2 NOT NULL,
                   CONSTRAINT PK_PHOTO PRIMARY KEY (ID, DELETED_AT),
                   MASTER_ID INTEGER NOT NULL,
                   MASTER_DELETED_AT DATETIME2 NOT NULL,
                   CONSTRAINT FK_PHOTO FOREIGN KEY (MASTER_ID, MASTER_DELETED_AT) REFERENCES PERSON(ID, DELETED_AT) ON UPDATE CASCADE,
                   CONSTRAINT FK_PHOTO2 UNIQUE (MASTER_ID, MASTER_DELETED_AT, DELETED_AT),
                   MODIFIED_AT DATETIME2 NOT NULL,
                   PHOTO VARCHAR(50) NOT NULL);

INSERT INTO PERSON VALUES (1, @UNDEFINED, @TIME1, 'John');
INSERT INTO PHOTO VALUES (1, @UNDEFINED, 1, @UNDEFINED, @TIME1, 'AAAAA');
SELECT * FROM PHOTO

-- SOFT UPDATE PERSON
INSERT INTO PERSON SELECT ID, @TIME2, MODIFIED_AT, NAME FROM PERSON WHERE ID = 1 AND DELETED_AT = @UNDEFINED;
INSERT INTO PHOTO (ID, DELETED_AT, MASTER_ID, MASTER_DELETED_AT, MODIFIED_AT, PHOTO) SELECT ID, @TIME2, MASTER_ID, @TIME2, MODIFIED_AT, PHOTO FROM PHOTO WHERE MASTER_ID = 1 AND DELETED_AT = @UNDEFINED;
UPDATE PERSON SET NAME = 'John2', MODIFIED_AT = @TIME2 WHERE ID = 1 AND DELETED_AT = @UNDEFINED;
SELECT * FROM PERSON LEFT JOIN PHOTO P ON PERSON.ID = P.MASTER_ID AND PERSON.DELETED_AT = P.MASTER_DELETED_AT WHERE '2030-03-06' BETWEEN PERSON.MODIFIED_AT AND PERSON.DELETED_AT AND '2030-03-06' BETWEEN P.MODIFIED_AT AND P.DELETED_AT;

-- SOFT DELETE PERSON
UPDATE PERSON SET DELETED_AT = @NOW WHERE ID = 1 AND DELETED_AT = @UNDEFINED;
UPDATE PHOTO SET DELETED_AT = @NOW WHERE MASTER_ID = 1 AND DELETED_AT = @UNDEFINED;
SELECT * FROM PERSON LEFT JOIN PHOTO P ON PERSON.ID = P.MASTER_ID AND PERSON.DELETED_AT = P.MASTER_DELETED_AT WHERE '2010-03-06' BETWEEN PERSON.MODIFIED_AT AND PERSON.DELETED_AT AND '2010-03-06' BETWEEN P.MODIFIED_AT AND P.DELETED_AT;

INSERT INTO PERSON VALUES (2, @UNDEFINED, @TIME1, 'Anthony');
INSERT INTO PHOTO VALUES (2, @UNDEFINED, 2, @UNDEFINED, @TIME1, 'AAAAA');

-- SOFT UPDATE PHOTO
INSERT INTO PHOTO (ID, DELETED_AT, MASTER_ID, MASTER_DELETED_AT, MODIFIED_AT, PHOTO) SELECT ID, @TIME2, MASTER_ID, MASTER_DELETED_AT, MODIFIED_AT, PHOTO FROM PHOTO WHERE MASTER_ID = 2 AND DELETED_AT = @UNDEFINED;
UPDATE PHOTO SET PHOTO = 'BBBBB', MODIFIED_AT = @TIME2 WHERE ID = 2 AND DELETED_AT = @UNDEFINED;
SELECT * FROM PERSON LEFT JOIN PHOTO P ON PERSON.ID = P.MASTER_ID AND PERSON.DELETED_AT = P.MASTER_DELETED_AT WHERE '2010-03-06' BETWEEN PERSON.MODIFIED_AT AND PERSON.DELETED_AT AND '2010-03-06' BETWEEN P.MODIFIED_AT AND P.DELETED_AT;
INSERT INTO PHOTO VALUES (4, @UNDEFINED, 2, @UNDEFINED, '2000-01-01', 'CCCCC'); -- DOESN'T WORK CAUSE THERE IS A PHOTO!

-- SOFT DELETE PHOTO
UPDATE PHOTO SET DELETED_AT = '2020-05-05' WHERE MASTER_ID = 2 AND DELETED_AT = @UNDEFINED;

DROP TABLE PHONE;
DROP TABLE PHOTO
DROP TABLE PERSON;
